# Site settings
title: LACKAWANNA EXPRESSO
SEOTitle: DotIN13's Blog
header-img: img/home-bg.jpg
email: dotin13@126.com
description: "Geek - Android, Linux. Politics - America, China. Think Global with DotIN13"
keyword: "DotIN13, Android, Linux, Politics"
url: "https://www.wannaexpresso.com"              # your host, for absolute URL
baseurl: ""                            # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
weibo_username:     DotIN13
#zhihu_username:     huxpro
github_username:    DotIN13
twitter_username:   DotIN13
facebook_username:  peter.zhang.1466
#linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: none
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: ["jekyll-paginate"]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    disable: true
    #span:
    #  line_numbers: false
    #block:
    #  line_numbers: true
    #  start_line: 1

# Gittalk settings
gitalk_clientid: false
# b4edc9ea059838b0bf4e

# Disqus settings
disqus_username: dotin13

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: "UA-159368053-1"            # Format: UA-xxxxxx-xx
ga_domain: "www.wannaexpresso.com"



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Squeeze alla juice outta it!"
sidebar-avatar: /img/orange.webp      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
    {
        title: "Tassadar",
        href: "https://www.facebook.com/profile.php?id=100012878798046"
    },{
        title: "Songqing Ye",
        href: "https://www.facebook.com/profile.php?id=100012994265703"
    },{
        title: "练习小册",
        href: "https://lhr.wiki/"
    },{
        title: "陆陆侠",
        href: "https://llx.life/"
    }

]
